### ISSUE TITLE
NullPointerException while calling signinWithRefreshToken 

### ISSUE THREAD

**Issue by sabyasachiRepo** [ibm-cloud-security/appid-clientsdk-android#137]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.ibm.cloud.appid.android.internal.authorizationmanager.AuthorizationManager com.ibm.cloud.appid.android.internal.OAuthManager.getAuthorizationManager()' on a null object reference

**Comment by motyd** [comment]
Can you provide the following:
- SDK Version
- Usage code + how to reproduce
- Stack Trace
- Device and OS version info

Does this happen always? Only on in some cases?

**Comment by sabyasachiRepo** [comment]
SDK: 4.0.2

**Code**
 Context context = OurApp.getInstance();
                CountDownLatch countDownLatch = new CountDownLatch(1);
                new AppExecutors().networkIO().execute(new Runnable() {
                    @Override
                    public void run() {
                        String refreshTokenString = SharedPreferencesHelper.getSharedPrefString(context, AppConstants.REFRESH_TOKEN);
                       OurApp.getInstance().getAppID().signinWithRefreshToken(context, refreshTokenString, new AuthorizationListener() {
                            @Override
                            public void onAuthorizationFailure(AuthorizationException exception) {
                                authenticationSuccessful = false;
                                countDownLatch.countDown();
                            }

                            @Override
                            public void onAuthorizationCanceled() {
                                authenticationSuccessful = false;
                                countDownLatch.countDown();
                            }

                            @Override
                            public void onAuthorizationSuccess(AccessToken accessToken, IdentityToken identityToken, RefreshToken refreshToken) {
                                //User authenticated
                                SharedPreferencesHelper.setSharedPrefString(context, AppConstants.ACCESS_TOKEN, accessToken.getRaw());
                                SharedPreferencesHelper.setSharedPrefString(context, AppConstants.REFRESH_TOKEN, refreshToken.getRaw());
                                authenticationSuccessful = true;
                                countDownLatch.countDown();
                            }
                        });
                    }
                });
**how to reproduce**
Not able to reproduce at our end. Client facing the issue as reported by firebase crashlytics.
**Stack  trace:** 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ibm.cloud.appid.android.internal.authorizationmanager.AuthorizationManager com.ibm.cloud.appid.android.internal.OAuthManager.getAuthorizationManager()' on a null object reference
       at com.ibm.cloud.appid.android.api.AppID.signinWithRefreshToken(AppID.java:245)
       at com.kone.equipmentadvisor.api.NetworkManager$1$1.run(NetworkManager.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Device and OS**
Galaxy S5 Neo (5.1.1)

It does not happen always. Not sure if some user facing it frequently or in some scenarios

**Comment by motyd** [comment]
From #136:

> SDK version:4.0.2
> 
> Get to know this issue from firebase crashlytics report. Not sure about origin.
> 
> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.ibm.cloud.appid.android.internal.OAuthManager com.ibm.cloud.appid.android.internal.authorizationmanager.AuthorizationFlowContext.getOAuthManager()' on a null object reference
> at com.ibm.cloud.appid.android.internal.authorizationmanager.ChromeTabActivity.onCreate(ChromeTabActivity.java:61)
> at android.app.Activity.performCreate(Activity.java:6550)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3233)
> at android.app.ActivityThread.access$1000(ActivityThread.java:197)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:145)
> at android.app.ActivityThread.main(ActivityThread.java:6873)
> at java.lang.reflect.Method.invoke(Method.java)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
> 
> It does not happen frequently as per crash report.  But it does happen.  
>

**Comment by motyd** [comment]
Let me point out that if you are unable to reproduce this, it makes troubleshooting the issue very difficult as we do not have a way to reproduce this either.

That being said, to provide further assistance we will need the following information:
1. What is `OurApp`? does this extend Android's `Application` class? 
2. Can we see the code for `OurApp`?
3. Where and how is the App ID SDK being initialized? In an Activity? In `OurApp`? etc... Specifically where does the call to `initialize(context, tenantId, region)` happen?

**Comment by shiranyo** [comment]
Closing
